### ISSUE TITLE
Count Threshold Per Item

### ISSUE THREAD

**Issue by gviscardi** [Noshei/GatheringTracker#10]
Would it be possible to have a running count threshold (total required) per item tracked (i.e. Fel Iron Ore 134/230)?

**Comment by Noshei** [comment]
That's an interesting idea.  Would you want to be able to set the threshold separately for each item?

**Comment by gviscardi** [comment]
Yes, thats exactly what I was thinking

**Comment by Noshei** [comment]
This has been implemented through the new Alerts system.
