### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Mrmannic** [Noshei/GatheringTracker#11]
I think when I get a new item from the mailbox too fast. I'll get an error message, which will then mess with your add-on till i reset the ui. I just downloaded tradeskillmaster and haven't had a problem till i downloaded that. 

Date: 2024-01-26 12:59:24
ID: -7
Error occured in: Global
Count: 356
Message: ...terface/AddOns/GatheringTracker/GatheringTracker.lua line 699:
   attempt to index field 'countTotal' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:699: ?()
   [string "@Interface/AddOns/GatheringTracker/Utilities.lua"]:89:
      Interface/AddOns/GatheringTracker/Utilities.lua:83
Locals:
(*temporary) = <function> defined =[C]:-1

Date: 2024-01-29 13:18:48
ID: 1
Error occured in: Global
Count: 1
Message: ...terface/AddOns/GatheringTracker/GatheringTracker.lua line 699:
   attempt to index field 'countTotal' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:699: ?()
   [string "@Interface/AddOns/GatheringTracker/Utilities.lua"]:89:
      Interface/AddOns/GatheringTracker/Utilities.lua:83
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  AdvancedInterfaceOptions, v1.8.14
  AltVault, v2.1.6
  Auctionator, v10.2.16
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  BadBoy, vv10.2.2
  BagBrother, v
  Bagnon, v10.2.17
  Bartender4, v4.14.13
  BattleGroundEnemies, v10.2.0.3
  Collectionator, v1.18
  CurrencyTracking, vv7.16
  Details, v#Details.20240122.12237.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDisenchantRevamped, v1.0.0
  Enchantrix, v9.1.BETA.5.13 (OneMawTime)
  FarmHud, v9.2.8-release
  FarmHudQuestArrow, v9.2.8-release
  Gathering, v2.13
  GatheringTracker, v2.0.1
  GatherMate2, v1.48.8
  Informant, v9.1.BETA.5.13 (OneMawTime)
  InstanceAchievementTracker, v4.35.0
  ItemLock, v0.11.9
  MinimapAlert, v21
  MinimapRangeExtender, vv7
  Molinari, v100200.110-Release
  MountCollector, v2.8.2
  NameplateCooldowns, v100205.1-release
  NPCTime, v1.0.18
  Postal, vv4.1.1
  Reputations, v1.12
  SilverDragon, vv2024.1.1
  SilverDragonOverlay, vv2024.1.1
  SilverDragonRangeExtender, vv2024.1.1
  SlideBar, v9.1.BETA.5.13 (OneMawTime)
  SparkleSwap, v1.5
  SpeedyAutoLoot, v2.2.15
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  TomTom, vv3.5.5-release
  TradeSkillMaster, vv4.13.18
  TradeSkillMasterAppHelper, vv4.13.1
  WorldBossTimers, vv1.12.4
  BlizRuntimeLib v10.2.5.53040(US) <enUS>
  (ck=616)

**Comment by Mrmannic** [comment]
I take it back, it now always pops up as soon as I log in.

**Comment by jengel39** [comment]
Thanks for letting me know.  I'll take a look into this.

Can you post a screen shot of your settings, particularly the Look and Feel tab.

**Comment by jengel39** [comment]
Based on the error, I'm guessing you might also have notifications enabled, can you post a screen shot of the notification tab settings as well.

**Comment by Noshei** [comment]
Thanks for letting me know. I'll take a look into this.

Can you post a screen shot of your settings, particularly the Look and Feel tab.

Based on the error, I'm guessing you might also have notifications enabled, can you post a screen shot of the notification tab settings as well.

**Comment by Mrmannic** [comment]
My notifications were turned off. but here is the screenshot of the look and feel. The bug can pop up when I log in, but can stop from popping up if the wow application is turned off and reopened.  When I click on my professions button and when I switch from journal to specialization it pops up sometimes.

![look and feel](https://github.com/Noshei/GatheringTracker/assets/158093096/09e491d3-4a08-414a-becb-cc3c931321cb)
![notifications screen shot](https://github.com/Noshei/GatheringTracker/assets/158093096/c307bab8-46d1-49fe-92bb-0f9289d02301)

**Comment by Noshei** [comment]
do any other errors show up, even if they are for other addons?

I've not been able to reproduce the same error you are getting, but I did get a different error that may be related.  I've resolved the error I was able to get and pushed an update for that.  If you can get the new version and let me know if you are still getting any errors (and what they are, if you get any) I would appreciate it.

**Comment by Mrmannic** [comment]
At the moment I'm not receiving any other errors but I'll get back to you if I do. 

Thank you

**Comment by Mrmannic** [comment]
I spoke to soon and just got this error was prospecting Ores
![error 2](https://github.com/Noshei/GatheringTracker/assets/158093096/9047f2b2-ac5f-4bb6-bf16-4c8e6b44b561)


Date: 2024-01-29 21:06:45
ID: 1
Error occured in: Global
Count: 1
Message: ...terface/AddOns/GatheringTracker/GatheringTracker.lua line 653:
   attempt to index field '?' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:653: ?()
   [string "@Interface/AddOns/GatheringTracker/Utilities.lua"]:89:
      Interface/AddOns/GatheringTracker/Utilities.lua:83
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  AdvancedInterfaceOptions, v1.8.14
  AltVault, v2.1.6
  Auctionator, v10.2.16
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  BadBoy, vv10.2.2
  BagBrother, v
  Bagnon, v10.2.18
  Bartender4, v4.14.13
  BattleGroundEnemies, v10.2.0.3
  Collectionator, v1.18
  CurrencyTracking, vv7.16
  Details, v#Details.20240122.12237.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDisenchantRevamped, v1.0.0
  Enchantrix, v9.1.BETA.5.13 (OneMawTime)
  FarmHud, v9.2.8-release
  FarmHudQuestArrow, v9.2.8-release
  Gathering, v2.13
  GatheringTracker, v2.0.2
  GatherMate2, v1.48.8
  Informant, v9.1.BETA.5.13 (OneMawTime)
  InstanceAchievementTracker, v4.35.0
  ItemLock, v0.11.9
  MinimapAlert, v21
  MinimapRangeExtender, vv7
  Molinari, v100200.110-Release
  MountCollector, v2.8.2
  NameplateCooldowns, v100205.1-release
  NPCTime, v1.0.18
  Postal, vv4.1.1
  Reputations, v1.12
  SilverDragon, vv2024.1.1
  SilverDragonOverlay, vv2024.1.1
  SilverDragonRangeExtender, vv2024.1.1
  SlideBar, v9.1.BETA.5.13 (OneMawTime)
  SparkleSwap, v1.5
  SpeedyAutoLoot, v2.2.15
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  TomTom, vv3.5.5-release
  TradeSkillMaster, vv4.13.18
  TradeSkillMasterAppHelper, vv4.13.1
  WorldBossTimers, vv1.12.4
  BlizRuntimeLib v10.2.5.53040(US) <enUS>
  (ck=616)

**Comment by Noshei** [comment]
ok, I just pushed out 2.0.3.  It should hit Curse and others in about 15 minutes or so.  This should resolve the latest error you got.  Hopefully no more errors after that, but if there are I'll keep swatting them!

**Comment by Mrmannic** [comment]
Got this error when I got a lot of armor from the mailbox. let me update the addon to the new one you just pushed out.
![mail error](https://github.com/Noshei/GatheringTracker/assets/158093096/cb3b3459-497a-4d0d-afdd-c2c923a4537b)

Date: 2024-01-29 23:18:31
ID: 1
Error occured in: Global
Count: 17
Message: ...terface/AddOns/GatheringTracker/GatheringTracker.lua line 699:
   attempt to index field 'countTotal' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:699: ?()
   [string "@Interface/AddOns/GatheringTracker/Utilities.lua"]:89:
      Interface/AddOns/GatheringTracker/Utilities.lua:83
Locals:
(*temporary) = <function> defined =[C]:-1

AddOns:
  Swatter, v9.1.BETA.5.13 (OneMawTime)
  AdvancedInterfaceOptions, v1.8.14
  AltVault, v2.1.6
  Auctionator, v10.2.16
  Auctioneer, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerStatsOverTime, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilDealFinder, v9.1.BETA.5.13 (OneMawTime)
  AuctioneerUtilValuer, v9.1.BETA.5.13 (OneMawTime)
  BadBoy, vv10.2.2
  BagBrother, v
  Bagnon, v10.2.18
  Bartender4, v4.14.13
  BattleGroundEnemies, v10.2.0.3
  Collectionator, v1.18
  CurrencyTracking, vv7.16
  Details, v#Details.20240122.12237.155
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  EasyDisenchantRevamped, v1.0.0
  Enchantrix, v9.1.BETA.5.13 (OneMawTime)
  FarmHud, v9.2.8-release
  FarmHudQuestArrow, v9.2.8-release
  Gathering, v2.13
  GatheringTracker, v2.0.2
  GatherMate2, v1.48.8
  Informant, v9.1.BETA.5.13 (OneMawTime)
  InstanceAchievementTracker, v4.35.0
  ItemLock, v0.11.9
  MinimapAlert, v21
  MinimapRangeExtender, vv7
  Molinari, v100200.110-Release
  MountCollector, v2.8.2
  NameplateCooldowns, v100205.1-release
  NPCTime, v1.0.18
  Postal, vv4.1.1
  Reputations, v1.12
  SilverDragon, vv2024.1.1
  SilverDragonOverlay, vv2024.1.1
  SilverDragonRangeExtender, vv2024.1.1
  SlideBar, v9.1.BETA.5.13 (OneMawTime)
  SparkleSwap, v1.5
  SpeedyAutoLoot, v2.2.15
  Stubby, v9.1.BETA.5.13 (OneMawTime)
  TomTom, vv3.5.5-release
  TradeSkillMaster, vv4.13.18
  TradeSkillMasterAppHelper, vv4.13.1
  WorldBossTimers, vv1.12.4
  BlizRuntimeLib v10.2.5.53040(US) <enUS>
  (ck=616)

**Comment by Mrmannic** [comment]
just updated to 2.0.3 I'll try to see if I can get the error again the same way

**Comment by Mrmannic** [comment]
yeah it happened again.

**Comment by Noshei** [comment]
hmm, thats the original error at least.  Were you just collecting gear from the mail when it happened?

**Comment by Noshei** [comment]
What do you have selected for filters when you got this error?

**Comment by Mrmannic** [comment]
> hmm, that's the original error at least. Were you just collecting gear from the mail when it happened?

yes, I was collecting the gear. I clicked open all mail. Also if you talking about what's under the general tab the filters I put are nothing if that's what you are referring to.

![general tab](https://github.com/Noshei/GatheringTracker/assets/158093096/e71ee25f-2720-4553-ab7e-63de29a2f5d9)

**Comment by Noshei** [comment]
No, I mean if you click on the + next to Gathering Tracker and click Filters, what you have selected in there.  Like these:
![image](https://github.com/Noshei/GatheringTracker/assets/8866000/d5a16dd2-46fb-410f-804a-c6613911ecc6)

**Comment by Noshei** [comment]
ok, I pushed another update.  This one should resolve the error.

**Comment by Mrmannic** [comment]
Sorry didn't know, let me try the new update and then get back to you. but I have quite the filters clicked and marked.

**Comment by Mrmannic** [comment]
It didn't show up! great job!

Many thanks

**Comment by Noshei** [comment]
Good to hear, feel free to reopen this or open a new ticket if you get any further issues.
