### ISSUE TITLE
Feature Request: Timer/Gold per Hour

### ISSUE THREAD

**Issue by KarraganEU** [Noshei/GatheringTracker#12]
A simple start/stop/reset timer that can show the gold per time unit of the gathered items with your set TSM price Source would be neat. Easy to compare multiple routes and have a quick overview of farming efficiency.

**Comment by Noshei** [comment]
I've considered this a number of times, and it is on my list of things to add at some point.

**Comment by Noshei** [comment]
This has been added in v2.3.0.
