### ISSUE TITLE
[Feature Request] Adding Profession Knowledge Items

### ISSUE THREAD

**Issue by Starlynk1** [Noshei/GatheringTracker#13]
Something that I always forget to check and see if I gathered is Profession Knowledge items. These are very important and I also find it hard to find in our bags because they are just mixed with everything else.

What I would like to ask for is that these items show in the tracker and the ability to use them directly from the tracker as a button. This would make this addon quite honeslty the perfect gathering addon. (some would say we need per hour tracking, but I walk away frequently XD)

**Comment by Noshei** [comment]
I will have to think about this some more.  Generally, I only add crafting materials to the filters, though I have made a few exceptions.

As for having something to click to use the Knowledge items, I am unlikely to add that.  The display is intentionally not clickable to prevent it from getting in the way while playing.  I will still consider this, but it may not happen for a while (if at all)

**Comment by Starlynk1** [comment]
Thanks for the quick response on this. If not clickable, that's ok. Just knowing I gathered the items would be beneficial enough to know that I have them.

**Comment by Starlynk1** [comment]
So I've found the way in your addon to use the Custom tab to add these items. Also I installed an addon called 'Can Opener' that displays a clickable button showing what can be used. 

So you can delay any feature updates regarding this however I would appreciate it if these could be added still. Maybe if you can add the item ID's to th respective professions for the on use items? As for clickable, would be cool to see it in the addon so we wouldn't need 2 addons to accoomplish this feature request.

Thanks again and if you need anyone to help test updates, let me know.

**Comment by Noshei** [comment]
I've added the TWW Knowledge Items in [v2.0.11](https://github.com/Noshei/GatheringTracker/releases/tag/2.0.11), I'm not sure if I'll add the DF ones as I struggled to find a good list.

I won't be making anything clickable to use the items.  This requires special code as using items is highly restricted to prevent abuse.  So adding that extra code would be a significant change for something not in scope for this addon.

**Comment by Starlynk1** [comment]
Sounds good. Thanks again.
Sent from my iPhone

On Sep 2, 2024, at 15:47, Noshei ***@***.***> wrote:

﻿

I've added the TWW Knowledge Items in v2.0.11<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Noshei_GatheringTracker_releases_tag_2.0.11&d=DwMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=XodWtLBkFpvdbc-aEppP_ibPteZq0Cpnye3A6MMh-wk&m=Pota_7MN9mrMRpjXbRT-b1vxfYHYeWNhaZYUMejL2ZnErHCVFAsy4_wlIH7qTTJR&s=kJLQQdqpm1E8d6sLwTeZdea4iiaRkeX4cBbfK8Jalqs&e=>, I'm not sure if I'll add the DF ones as I struggled to find a good list.

I won't be making anything clickable to use the items. This requires special code as using items is highly restricted to prevent abuse. So adding that extra code would be a significant change for something not in scope for this addon.
