### ISSUE TITLE
[Feature Request] Select All Option

### ISSUE THREAD

**Issue by Starlynk1** [Noshei/GatheringTracker#14]
Can you add a Select All button for each of the profession areas in the filter. Lots of wasted clicking when I am pretty sure most people will want to start tracking all mats for that profession and then limit what to see later on.

Thank you

**Comment by Noshei** [comment]
Right now I dont have a good way to add this to the filter options in the Settings.  However, if you enable the Filter Menu you can do that from there as each expansion and category can be selected to enable/disable everything under it.

**Comment by Starlynk1** [comment]
I looked around for the filter button and discovered that due to my frame location (upperleft at window edge), the filter button was not showing. Any way to have it moved or the option to place it elsewhere on the main frame so it doesn't become 'lost'?

Also, something that may help is using code to keep the frame from leaving the visible area. I can't remember the code snippet for this but if I find it I will share that.

**Comment by Noshei** [comment]
So I have plans to add broker and minimap options for the filter menu, so that should help, but I can also work on having it be movable independent of the main display.

I should be able to figure out how to prevent the display from being moved outside the bounds of the window.

**Comment by Noshei** [comment]
I've added the windows bounds to the display, it still allows for the filter button to be outside of the display, but I'll work on that eventually.

**Comment by Noshei** [comment]
I just added broker support and a minimap icon with v2.4.0, the icons will provide access to the filter menu even when the filter icon isn't enabled/visible.

I still need to work on not allowing the F button to be moved off-screen.

**Comment by Noshei** [comment]
v2.5.1 now had code to prevent the Filter Button from being stuck off-screen.  If you move the display to a position where the filter button would be off-screen the button will be moved to an on-screen location.
