### ISSUE TITLE
[Bug] Does not hide during Follower Dungeons

### ISSUE THREAD

**Issue by Starlynk1** [Noshei/GatheringTracker#15]
I checked the settings and there is no option to hide during follower dungeons. Not sure how they are any different on the check side of things, but this may be a general issue in all dungeons and it showing. Haven't tested that yet.

**Comment by Noshei** [comment]
There is no option to hide during dungeons or raids currently, though the group options sorta cover this in most cases if you have it disabled.

I will look into adding an option to have it hidden in instanced content (dungeons, raids, islands, PVP, etc).

**Comment by Noshei** [comment]
I've added a new option to have the display hide when in instances, this will be available in v2.0.13.

**Comment by Starlynk1** [comment]
Not sure if the recent update addresses this, but the hide during instances is not working correctly. If the tracker is already showing and you enter an instance, it will continue to display. You can turn it on and back on using the minimap button and while in an instance it will not show up again.

Seems to not be checking if its in an instance during a zone change.

**Comment by Noshei** [comment]
I think this was related to the error you posted.  In my testing, this is now working with v2.2.1.

**Comment by Noshei** [comment]
it checks for instances, delves might be set up differently though.  I'll have to try and find a way to test this, as I don't have TWW to do a delve.

**Comment by Noshei** [comment]
oh I meant to ask, were you in a party or solo when you ran the delve?

**Comment by Starlynk1** [comment]
I am normally doing these solo and can't remember what happens when in a group. Strange thing about delves is that not sure the zone change event triggers or not based on how it loads. It's not a normal portal into an instance, it's activate the delve and the fog that was blocking you disappears to let you enter. No transition noticed besides that. Possibly why once you are in a delve, you can hide the tracker and unhide it and it doesn't show up again due to being in the delve.

I will see what I can find as well, may need to use a different event for delves.

**Comment by Starlynk1** [comment]
Found the problem, there was a mode check with with a retun before the hide check. Here is the lua file for that change. I did add zone_changed event handler, but that most likely won't be needed as its handle in the inventoryupdate function.

Moving the mode check to after the hide check fixed it as far as I can tell with testing.
[GatheringTracker.lua.zip](https://github.com/user-attachments/files/17048384/GatheringTracker.lua.zip)

**Comment by Noshei** [comment]
Ah I see what you changed.  I did end up getting TWW, so I should be able to get into a delve to test this in the next day or so.

**Comment by Starlynk1** [comment]
I would say that the zone_changed event handler isn't needed or the other zonechanged items I added. Pretty sure just moving the mode check below the inventory update would work.

**Comment by Noshei** [comment]
ok, this should now be resolved with v2.3.1.  I went a different direction from what you suggested.
