### ISSUE TITLE
2.2.1 will not work, even if I disable all other addons

### ISSUE THREAD

**Issue by J-o-h-n-M** [Noshei/GatheringTracker#18]
Message: ...terface/AddOns/GatheringTracker/GatheringTracker.lua:399: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Sun Sep 15 13:32:19 2024
Count: 1
Stack: ...terface/AddOns/GatheringTracker/GatheringTracker.lua:399: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:399: in function `AllignRows'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:713: in function `PrepareDataForDisplay'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:889: in function `ProcessSoloData'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:852: in function `?'
[string "@Interface/AddOns/GatheringTracker/Utilities.lua"]:89: in function <Interface/AddOns/GatheringTracker/Utilities.lua:83>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by J-o-h-n-M** [comment]
I get this message as soon as I log in

**Comment by J-o-h-n-M** [comment]
Also get this after I check my email:

Message: ...terface/AddOns/GatheringTracker/GatheringTracker.lua:399: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Sun Sep 15 13:36:52 2024
Count: 1
Stack: ...terface/AddOns/GatheringTracker/GatheringTracker.lua:399: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:399: in function `AllignRows'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:713: in function `PrepareDataForDisplay'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:889: in function `ProcessSoloData'
[string "@Interface/AddOns/GatheringTracker/GatheringTracker.lua"]:852: in function `?'
[string "@Interface/AddOns/DBM-Core/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/DBM-Core/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ore/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/DBM-Core/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Decursive/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <.../AddOns/Decursive/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by Noshei** [comment]
This should be resolved in v2.2.2.  Please let me know either way.

**Comment by J-o-h-n-M** [comment]
2.2.2 seems to have fixed it indeed. Thanks for the quick reply and fix!
