### ISSUE TITLE
Friends Tracker Not showing anything with Group sync on

### ISSUE THREAD

**Issue by Maxilees** [Noshei/GatheringTracker#2]
Hi, My friend and I have installed the added however my friend's tracker is not showing anything, we have checked the settings and the herbs are turned on and the addon is sending me the group data. 
![image](https://user-images.githubusercontent.com/74764244/99779655-7df99080-2b69-11eb-847f-f72bfa7cf1c2.png)
![image](https://user-images.githubusercontent.com/74764244/99779715-92d62400-2b69-11eb-90d2-80b87304c39c.png)

**Comment by Noshei** [comment]
Can you provide a screenshot of the settings for your friend.
