### ISSUE TITLE
[Enhancement] Display Items (per Session)

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#22]
Add an additional option to just Display Items (per Session, i.e. since the last reset). This can (optionally) replace the Display Items per Hour. Same option for Gold per Hour.

If we can agree on (i.e. if you want to suggest an) implementation strategy, I would be willing to attempt to code it.

**Comment by b-morgan** [comment]
My first thought is to change the two options "Display Items per Hour" and "Display Gold per Hour" into three or four options, "Display Items", "per Hour", Display Gold", "per Hour" (three options would eliminate the first "per Hour").

The display would conditionalize the "/h" controlled by the above options.

**Comment by Noshei** [comment]
So you want to display both the total count for items and the count for items collected in the session?

**Comment by b-morgan** [comment]
My first thought is to just change the "per Hour" to be raw items so there would be two counts for each item. I could see a case where the total count could be optioned as well so it would be possible to just display the "session" item count (or items per hour).

I think this might make more sense if issue #23 were also implemented.

**Comment by Noshei** [comment]
I wouldn't want to change the per hour display, but I could add a session count option.

**Comment by b-morgan** [comment]
I'll add some context to what I'm trying to measure. I have a tailor who is farming Follower Dungeons for cloth. There are eight instances and I'd like to know which one(s) yield the most cloth either per run or per hour.

**Comment by b-morgan** [comment]
I'd accept adding the per session count as long as I can select which of the three counts were displayed. I want to leave at least some of my screen to the game itself :-)

**Comment by Noshei** [comment]
Yeah, any columns I add always have an option to hide them.  So I would add an option to show the session count and a sub-option to hide the total count.

**Comment by Noshei** [comment]
Have a look at v2.6.0.  I just pushed it out (should be available on curse shortly).  I believe this will give you want you are looking for.  Let me know, if you were looking for anything different or if I missed something.

**Comment by b-morgan** [comment]
Excellent! I was going to offer to test an alpha release.

I did discover one unexpected issue, changing the filter clears the session only data. I was testing with only Ore selected and then decided to add Fish (which missed a species, I'll open another issue on that).

**Comment by Noshei** [comment]
Session data only gets removed if you remove an item from the filter.  It should get removed if you add/remove items that you haven't collected in that session.  And this can't change, because once unselect a filter for an item, the addon removes all data for that item to ensure nothing shows up that isn't selected.

**Comment by Noshei** [comment]
I'm gonna go ahead and close this request at this time.
