### ISSUE TITLE
[Enhancement] Only display items gathered since last reset.

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#23]
Rather than filling the screen with all the items selected, just display those items collected since the last "Reset Item and Gold per Hour".

**Comment by Noshei** [comment]
Is this different than your other post?

**Comment by Noshei** [comment]
ah ok, so you are wanting an option to only display items that have been collected in the current session.  I should be able to do that.

**Comment by b-morgan** [comment]
Issues #22 and #23 could easily be combined into one. I made them separate as the implementation of #23 might be harder than the implementation of #22.

**Comment by Noshei** [comment]
yeah I'm going to add this into #22, closing this one and will use #22
