### ISSUE TITLE
Add Reagent Bank and Warband Bank

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#24]
My meager Git knowledge has failed me. I don't know how to get my fork to match your 2.6.0 changes so I can't figure out how to do a pull request for the following changes.

Blizzard has deprecated `GetItemCount` and it will be removed in the future. The replacement is `C_Item.GetItemCount` and there are some new [parameters](https://warcraft.wiki.gg/wiki/API_C_Item.GetItemCount).

I have incorporated these new parameters by adding two new checkboxes. My changes are included in the .zip file below.

[GatheringTracker.zip](https://github.com/user-attachments/files/17450949/GatheringTracker.zip)

Note: I am the current author/maintainer of [Skillet](https://github.com/b-morgan/Skillet) on retail and [Skillet-Classic](https://github.com/b-morgan/Skillet-Classic) on Cataclysm Classic and Classic Era. I've managed to learn enough Git commands to manage those repositories and publish releases on CurseForge but not enough Git knowledge to handle another push request to you.

**Comment by Noshei** [comment]
This is how you sync your fork from the upstream repo: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

I'll take a look at this, should be easy enough to get added.

**Comment by Noshei** [comment]
Pushed v2.6.1 with these changes.
