### ISSUE TITLE
[Enhancement] Tooltip for items on screen

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#25]
I'd like to see a tooltip, name only is fine, for the items on the screen.

**Comment by Noshei** [comment]
I'll look into this, but I'm always hesitant to do anything that requires mouse interaction, as I do not want this addon to interfere with gameplay and block mouse functionality.

**Comment by b-morgan** [comment]
Maybe as an option? My 74 year old eyes (and brain) sometimes need a bit of extra help!

**Comment by Noshei** [comment]
added in v2.6.2.  I went ahead and just used the normal tooltip, as that seemed easier than making one with just the name.
