### ISSUE TITLE
Tooltip missing from first item on screen

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#27]
When Display Item Tooltip is checked, the first item on screen is missing the tooltip.

**Comment by b-morgan** [comment]
This appears to happen when the General, Filters Button option is checked.

**Comment by Noshei** [comment]
ah, this is a dumb issue I didn't think about.  There is an invisible frame around the filter button that is used to make it easier to find when the fade option is used.  I've not looked yet, but I'm 100% sure that this is the issue.  I'll have to move that frame behind the icon texture.
