### ISSUE TITLE
Error on WoW 11.0.5

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#28]
I'm not sure this is due to something Blizzard changed in 11.0.5. I just entered a follower instance with my Tailor / Engineer to farm more cloth and scraps.

```
4x GatheringTracker/GatheringTracker.lua:383: bad argument #1 to 'SetWidth' (Usage: self:SetWidth(width))
[string "=[C]"]: in function `SetWidth'
[string "@GatheringTracker/GatheringTracker.lua"]:383: in function `AllignColumns'
[string "@GatheringTracker/GatheringTracker.lua"]:571: in function `PrepareDataForDisplay'
[string "@GatheringTracker/GatheringTracker.lua"]:908: in function `ProcessSoloData'
[string "@GatheringTracker/GatheringTracker.lua"]:864: in function `?'
[string "@GatheringTracker/Utilities.lua"]:107: in function <GatheringTracker/Utilities.lua:101>

Locals:
(*temporary) = FontString {
 textType = "count"
}
(*temporary) = nil
```

**Comment by Noshei** [comment]
Gah, stupid follower dungeons are such a pita!  I found the issue and should have a fix for it soon.

**Comment by Noshei** [comment]
should be fixed in v2.6.4

**Comment by Noshei** [comment]
actually, v2.6.4 will likely cause an error.  I'll have to get another update out.

**Comment by Noshei** [comment]
ok, just pushed v2.6.5.  This one should be fine.  I really need to stop working on new stuff in the master branch.

**Comment by b-morgan** [comment]
Follower dungeons are my salvation... Much higher cloth gathering rate than farming the landscape.

Thanks for your efforts!
