### ISSUE TITLE
2.6.5 not working in Follower Dungeons

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#29]
I can't get 2.6.5 to work in a follower dungeon.

**Comment by b-morgan** [comment]
I got it to work by commenting out the `if C_LFGInfo.IsInLFGFollowerDungeon() == true then`. I checked `/dump IsInGroup()` and it returns true for follower dungeons. Group Mode is set to Group and Solo.

**Comment by Noshei** [comment]
Can you post a screenshot of the General and Look and Feel tabs.  Everything is working just fine for me in follower dungeons.

**Comment by b-morgan** [comment]
![image](https://github.com/user-attachments/assets/26d827f3-09b0-4dc2-8825-050aaedc54e5)

![image](https://github.com/user-attachments/assets/77c63d1a-d7e7-4f4b-a1dc-17e50e826da3)

**Comment by b-morgan** [comment]
I get a lot of "You aren't in a party" in chat when I loot. Not sure if GT is causing these.

**Comment by b-morgan** [comment]
Just verified that it is GT by disabling it for a couple of pulls.

**Comment by Noshei** [comment]
I'm not getting any "You aren't in a party" messages on my end, but that line you commented out would likely cause that to happen.

I'm pretty sure I found the issue why it wasn't displaying anything for you, it was a logic issue related to how I initialize an item and store its data.  This is fixed in v2.6.6.

**Comment by b-morgan** [comment]
Just finished the follower dungeon. I'll download 2.6.6 and check it again.

**Comment by b-morgan** [comment]
Why do you want to return false when in follower dungeons?

**Comment by b-morgan** [comment]
Should the `IsInGroup()` calls in SetChatType be changed to `GT:IsInGroup()`?

**Comment by Noshei** [comment]
No, that is fine.  I only need GT:IsInGroup() in certain parts of the code.

**Comment by Noshei** [comment]
Gonna close this now, feel free to repost if its still not working.
