### ISSUE TITLE
Doesn't seem to be loading in the latest SL release

### ISSUE THREAD

**Issue by CSTufts** [Noshei/GatheringTracker#3]
could obviously be operator error, I can add filters and move the ui when I toggle the unlock frame in the settings, but nothing is actually getting displayed, I am using bagnon, though disabling it doesn't seem to help. 
not using any fancy overly like elvui, though I do have plater and WA though I can't see that they would be interfering...

any suggestions?

**Comment by CSTufts** [comment]
does seem to be updating the correct amount in the debug, its just not drawing anything in the ui

**Comment by Noshei** [comment]
Can you take some screenshots with the debug turned on so I can see what is happening.  And include screen shots of your settings.

**Comment by CSTufts** [comment]
see attached
![Screenshot (2)](https://user-images.githubusercontent.com/5683200/101270748-1dae4580-374a-11eb-9660-7974f48ab68b.png)
![Screenshot (3)](https://user-images.githubusercontent.com/5683200/101270749-1e46dc00-374a-11eb-86a4-9c209a2340fa.png)
![Screenshot (4)](https://user-images.githubusercontent.com/5683200/101270750-1e46dc00-374a-11eb-8791-bb75a5aed940.png)
![Screenshot (5)](https://user-images.githubusercontent.com/5683200/101270751-1edf7280-374a-11eb-9ade-7d5eb35bad82.png)
![Screenshot (6)](https://user-images.githubusercontent.com/5683200/101270753-1edf7280-374a-11eb-80fd-6e4d22992cd2.png)
![Screenshot (7)](https://user-images.githubusercontent.com/5683200/101270754-1f780900-374a-11eb-91d4-efb96b5399eb.png)

**Comment by CSTufts** [comment]
again, probably user error... you can see the filter button in the top left, which is where I am expecting the pane to display

**Comment by Noshei** [comment]
can you also attach the saved variables file.  You can find it at the following location.

In your WoW Directory, to do _retail_\WTF\Account\{AccountNameHere}\SavedVariables\GatheringTracker.lua

This is where the in game settings are saved.  I think what has happened is the display got detached from what is anchored to, which is causing problems, and the information in that file should tell me for sure.

**Comment by CSTufts** [comment]
[GatheringTracker.txt](https://github.com/Noshei/GatheringTracker/files/5648331/GatheringTracker.txt)

**Comment by Noshei** [comment]
Can you try going into the profile settings and creating a new profile, then switch to that profile and see if it starts working?

**Comment by CSTufts** [comment]
So I tried:
Creating a new profile
copying from default
resetting the profile to default (I did remember to bring back the filters)
fresh install (I removed the saved vars)
disabled all other addons

Anything else you can think of?
If you want to zoom / screen share I will likely be playing tonight

If you need some other logs I can send them over

**Comment by CSTufts** [comment]
meant to reply, it seems to be something with SL stuff. I can use it to show bag space and gold now, when I turn on SL filters it breaks

**Comment by Noshei** [comment]
We can do a zoom / screen share.  https://us05web.zoom.us/j/5054179500?pwd=ZWJnUjNuTUtMdUVWSEcrYWdITXl1Zz09

**Comment by CSTufts** [comment]
![image](https://user-images.githubusercontent.com/5683200/101286712-0eff7700-37ba-11eb-8403-e7098bfba14d.png)

**Comment by CSTufts** [comment]
Message: ...terface\AddOns\GatheringTracker\GatheringTracker.lua:546: attempt to index global 'TSM_API' (a nil value)
Time: Sun Dec  6 11:55:42 2020
Count: 1
Stack: ...terface\AddOns\GatheringTracker\GatheringTracker.lua:546: attempt to index global 'TSM_API' (a nil value)
[string "@Interface\AddOns\GatheringTracker\GatheringTracker.lua"]:546: in function `PrepareForDisplayUpdate'
[string "@Interface\AddOns\GatheringTracker\GatheringTracker.lua"]:499: in function `ResetDisplay'
[string "@Interface\AddOns\GatheringTracker\GatheringTracker.lua"]:452: in function <...terface\AddOns\GatheringTracker\GatheringTracker.lua:422>
[string "=[C]"]: ?
[string "=[C]"]: in function `Hide'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:200: in function `InterfaceOptionsFrame_Show'
[string "@Interface\FrameXML\InterfaceOptionsFrame.lua"]:242: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:222>

Locals: self = <table> {
 sender = <table> {
 }
 groupMode = "WHISPER"
 UpdateDisplay = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:701
 EnableModule = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 baseName = "GatheringTracker"
 IterateEmbeds = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 UnregisterComm = <function> defined @Interface\AddOns\GatheringTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Printf = <function> defined @Interface\AddOns\GatheringTracker\libs\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 wait = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:113
 ConfigUpdateReceived = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:982
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 DisableModule = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 AddComas = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:64
 media = <table> {
 }
 RegisterMessage = <function> defined @Interface\AddOns\GatheringTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\GatheringTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 TableFind = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:68
 SendCommMessage = <function> defined @Interface\AddOns\GatheringTracker\libs\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 UnregisterAllComm = <function> defined @Interface\AddOns\GatheringTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 FiltersButton = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:227
 RegisterEvent = <function> defined @Interface\AddOns\GatheringTracker\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 ResetDisplay = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:490
 ElvUI = false
 IterateModules = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 Display = <table> {
 }
 metaData = <table> {
 }
 OnInitialize = <function> defined @Interface\AddOns\GatheringTracker\GatheringTracker.lua:21
 NewModule = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 GetModule = <function> defined @Interface\AddOns\GatheringTracker\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Interface\AddOns\GatheringTracker\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 RebuildIDTables = <function> defined @Interface\AddOns\Gat

**Comment by Noshei** [comment]
I just pushed version 1.1.8, it is now available on curse and here on github.

**Comment by CSTufts** [comment]
Works perfectly thanks for all your help!
