### ISSUE TITLE
Session data sometimes doesn't show an item on first loot

### ISSUE THREAD

**Issue by Noshei** [Noshei/GatheringTracker#34]
When an item is first acquired (as in you didn't have any of it before, or you are only showing session data and it is the first time looted in the session) the displayed session data will not be updated for that item.

I'm aware of this issue, and it is due to how I currently store data about items and what filters are selected.  Currently, I don't store any data for a filtered item until that item has a count greater than 0 (unless you have selected the option to show items with 0 count).  Because of this, the first time an item is looted the session tracking starts with the current count of the item (aka the amount looted that first time).

To resolve this I need to start storing 0 counts for all filtered items, but this has impacts on performance and will require some work to ensure that items with 0 count don't get displayed.  So I need to refactor both the item and display handling to resolve this.

**Comment by b-morgan** [comment]
I noticed this today and was coming to report but you beat me to it 😁

**Comment by Noshei** [comment]
Yeah, I found it while I was working on v3.0.0.  I decided to just leave it for the moment as it will take a good bit of work to fix.  That said its at the top of my list and will hopefully be fixed in the next week or so.

**Comment by Noshei** [comment]
This should now be resolved in v3.0.2
