### ISSUE TITLE
Some items not showing with 3.0.2 

### ISSUE THREAD

**Issue by b-morgan** [Noshei/GatheringTracker#35]
With "Only Display Session Data" and the filter set to TWW Ore, some of the farmed ore is not showing up. Is there some stale data that needs to be cleaned up from earlier versions?

**Comment by Noshei** [comment]
Does it never show up?  Is it always the same item or different items?  If its the same item, what item?

**Comment by b-morgan** [comment]
I'm not sure because my Reagent Bag has ore from previous sessions so I'm not sure which exact items are missing. I just notice at the beginning of a session that I've hit a few ore deposits and either the list is empty or seems to be missing some of what I farmed.

I don't think it is an item missing from the database.

If I reset the session, it appears to work better. That's why I was asking if there is stale data that gets cleaned up with a reset that should have been cleaned up earlier.

I'll try to collect better data.

**Comment by Noshei** [comment]
Did you by chance do anything that would have reduced the amount of an item before you started gathering?  When you log in everything gets initialized based on what you have currently.  If you do some crafting/selling/etc and then go gathering, then the session data will be negative.

I need to add logic to prevent session data from being negative.  This is the only thing I can think of that might cause this.

**Comment by b-morgan** [comment]
That could very well be the issue. I have two toons with mining, one a Blacksmith and the other a Jewelcrafter. I have a third toon that is an Engineer and a Tailor. The miners transfer ore to the Warband bank for the Engineer to use. I did run out of ore in the Warband bank this morning so my miners added some of their ore to the bank before heading out to capture more.

**Comment by Noshei** [comment]
released v3.0.3 that should fix this.
