### ISSUE TITLE
nil value issues

### ISSUE THREAD

**Issue by Incendiaeternus** [Noshei/GatheringTracker#4]
Installed and trying to use this, but keep getting the lua error and the addon not showing up. 

Message: ...terface\AddOns\GatheringTracker\GatheringTracker.lua:509: attempt to index field 'baseFrame' (a nil value)
Time: Fri Dec 11 22:18:14 2020
Count: 19
Stack: ...terface\AddOns\GatheringTracker\GatheringTracker.lua:509: attempt to index field 'baseFrame' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:758: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\AddOns\GatheringTracker\GatheringTracker.lua"]:509: in function `?'
[string "@Interface\AddOns\GatheringTracker\GatheringTracker.lua"]:139: in function <...terface\AddOns\GatheringTracker\GatheringTracker.lua:134>

Locals: errMsg = "...terface\AddOns\GatheringTracker\GatheringTracker.lua:509: attempt to index field 'baseFrame' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:517
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:536
 num = 0
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:510
 AddonBlockedHandler = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by Noshei** [comment]
thats a really weird error.  Are there by chance any other errors as well, because this one by itself doesn't give me much information.

**Comment by Incendiaeternus** [comment]
This is the only other lua - only two show up and this one had to reload to populate. 

Message: ...terface\AddOns\GatheringTracker\GatheringTracker.lua:211: attempt to index field 'backdrop' (a nil value)
Time: Fri Dec 11 22:48:48 2020
Count: 1
Stack: ...terface\AddOns\GatheringTracker\GatheringTracker.lua:211: attempt to index field 'backdrop' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\GatheringTracker\GatheringTracker.lua"]:211: in function `CreateBaseFrame'
[string "@Interface\AddOns\GatheringTracker\Config.lua"]:610: in function <Interface\AddOns\GatheringTracker\Config.lua:552>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...\AddOns\DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by Noshei** [comment]
are you using ElvUI? and if so, what version?

**Comment by Incendiaeternus** [comment]
ElvUI 12.16 Shadow and Light 4.18

**Comment by Noshei** [comment]
can you post what other addons you have.  I suspect that you have an addon with an old version of a specific library and that is causing issues.

**Comment by Noshei** [comment]
actually, looking closer at that last error, what is that DataStore addon?

**Comment by Noshei** [comment]
I'm guessing it is related to Altoholic.

**Comment by Incendiaeternus** [comment]
DataStore is Altoholic database I believe

**Comment by Noshei** [comment]
do you know what version of altaholic you have?

**Comment by Incendiaeternus** [comment]
Altoholic-Trtail (teelo's Fork) Altoholic-9.0.2-009.zip

**Comment by Noshei** [comment]
Can you post a list of all of your addons.

**Comment by Noshei** [comment]
I might have a fix, I'm taking a stab in the dark just based off of that second error.  I went ahead and release 1.1.9, it should be live on curse soon, or you can get it here on github now.

**Comment by Incendiaeternus** [comment]
No lua errors and showing up fine now.

**Comment by Noshei** [comment]
great to hear.  Resolved with 1.1.9.
