### ISSUE TITLE
UI issue upon spec change

### ISSUE THREAD

**Issue by Kadomi** [Noshei/GatheringTracker#5]
When I change specs on a character with GT active, I get a big frame across the width of my screen from Gathering Tracker. Fix is to reload UI, but as I change specs frequently on my druid, this is a bit tedious. I use ElvUI, if that's relevant, and have included a screenshot.
![gathering-tracker](https://user-images.githubusercontent.com/48963926/103001075-94aa5300-452c-11eb-8883-0b471a44b1a4.PNG)

**Comment by Noshei** [comment]
Thanks for the report.  I will take a look at this and hopefully have an update soon.

**Comment by Noshei** [comment]
Hmm, I'm not able to replicate this.  What version of ElvUI and Gathering Tracker are you using?  For the version of Gathering tracker it should tell you in chat when you login or reload UI.

**Comment by Kadomi** [comment]
I am using ElvUI 12.16 and GT 1.1.9. It is of course possible another addon interferes, and I have only tried it on my druid who is my only gatherer at the moment.

**Comment by Noshei** [comment]
do you have any other elvui related addons?

**Comment by Kadomi** [comment]
I use BenikUI as addon to ElvUI. I will try to selectively disable addons to see if I can spot the culprit, if you cannot reproduce this issue.
