### ISSUE TITLE
Not a "true" issue

### ISSUE THREAD

**Issue by Karat017** [Noshei/GatheringTracker#6]
I just installed this addon last night. I am trying to use the custom filter (Panda cooking items not listed) but I am not having any luck. Is there a help file somewhere?

**Comment by Noshei** [comment]
no, there's not really a help file anywhere.  Can you post a screenshot of the custom filter as you have it setup.  And a link to the item you are trying to use in the custom filter.

**Comment by Karat017** [comment]
https://www.wowhead.com/item=74843/scallions is the item I'm trying to add (there will be others as none of the veggie items are listed)

![GT custom](https://user-images.githubusercontent.com/80928491/111710580-51583b80-8820-11eb-8684-baa6942008d1.png)

**Comment by Karat017** [comment]
Ok, cancel that... I was using the wrong ID.  Sorry, I've never used ID before.  :((

**Comment by Noshei** [comment]
yeah, I was about to explain that.
