### ISSUE TITLE
repeating error

### ISSUE THREAD

**Issue by Mikamue** [Noshei/GatheringTracker#8]
Every time World of Warcraft UI reloads, I am getting a Lua error.  This has been happening now for about 3 days.
I am currently tracking items:
Awakened Air
Awakened Earth
Awakened Fire
Awakened Frost
Awakened Order

The error seems to have started once I started tracking those items, though I'm not certain.

Screenshot and attached .txt file with error text.
![Screenshot 2023-06-05 162818](https://github.com/Noshei/GatheringTracker/assets/135666009/c89795d5-900e-4cbc-9dc0-759fbbb02aad)
[Lua-error-text.txt](https://github.com/Noshei/GatheringTracker/files/11657872/Lua-error-text.txt)

**Comment by Noshei** [comment]
Do you have TSM installed and if not, do you have any options that require TSM enabled?

**Comment by Mikamue** [comment]
Hello, thank you for such a quick response!

I do not have TSM installed, but do not (afaik) have any options enabled
that require it (only option I see that requires it is Enable Count
Notification, which is not checked).

**Comment by Noshei** [comment]
thats for the report, I found the issue and have pushed 1.4.12 to resolve this.  It should be up on curse and other sources in 30 minutes or so.
