### ISSUE TITLE
Feature: multi columns instead of 1 long column

### ISSUE THREAD

**Issue by Tanae** [Noshei/GatheringTracker#9]
I'm tracking multiple things across DF, and would like an option to have 2 or 3 columns instead of 1 long one.

**Comment by Noshei** [comment]
that is an interesting idea. I will look into if I can make it happen.

**Comment by Noshei** [comment]
This has been added in [v2.0.9](https://github.com/Noshei/GatheringTracker/releases/tag/2.0.9)
